name: Build Windows package

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        include:
          - name: windows-x64
            win7: OFF

          - name: windows7-x64
            win7: ON

    runs-on: windows-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: VCPKG
        run: |
          vcpkg.exe install zlib libpng liblzma \
            --triplet 'x64-windows-static'

      - name: Configure
        run: |
          cmake \
            -S . \
            -B ./build \
            -DCMAKE_BUILD_TYPE=Release \
            -DVCMIEXTRACT_WIN7=${{ matrix.win7 }} \
            --toolchain="$VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake" \
            -DVCPKG_TARGET_TRIPLET='x64-windows-static'

      - name: Build
        run: cmake --build ./build --config Release

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: vcmiextract-${{ matrix.name }}
          compression-level: 9
          path: ./build/Release/vcmiextract.exe