name: Build Windows packages

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        include:
          - name: windows-x64
            platform: msvc-x64
            os: windows-latest
            triplet: x64-windows-static
            win7: OFF

          - name: windows7-x64
            platform: msvc-x64
            os: windows-latest
            triplet: x64-windows-static
            win7: ON

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          vcpkg.exe install \
            zlib \
            libpng \
            liblzma \
            --triplet '${{ matrix.triplet }}'

      - name: Configure
        run: |
          cmake \
            -S . \
            -B ./build \
            -DCMAKE_BUILD_TYPE=Release \
            -DVCMIEXTRACT_WIN7=${{ matrix.win7 }} \
            --toolchain="$VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake" \
            -DVCPKG_TARGET_TRIPLET='${{ matrix.triplet }}'

      - name: Build
        run: cmake --build ./build --config Release

      - name: Package
        run: |
          cmake --install ./build \
            --config Release \
            --prefix ./package

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: vcmiextract-${{ matrix.name }}
          compression-level: 9
          path: ./package/